#Data will be fetched from config server with git location https://github.com/STPrasad-kjpt/Practice-21st-Feb-2026

#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/microservices
#spring.datasource.username=root
#spring.datasource.password=root

spring.application.name=employee-service
#server.port=8081
#spring.cloud.client.hostname=localhost
#server.servlet.context-path=/employee-service/api
#addressservice.context-path=/address-service/api
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#management.endpoints.web.exposure.include=*
spring.config.import=optional:configserver:http://localhost:8899